import type { TStructure } from './type';

export const MOCK_STRUCTURE: TStructure = {
  companyName: '한국부동산',
  totalMembers: 37,
  directors: [
    {
      memberId: 'd1',
      userId: 'u1',
      fullName: '김민준',
      avatarUrl: 'https://i.pravatar.cc/100?img=11',
      role: '총괄',
      roleSlug: 'director',
      isMe: true,
    },
    {
      memberId: 'd2',
      userId: 'u2',
      fullName: '홍길동',
      avatarUrl: 'https://i.pravatar.cc/100?img=12',
      role: '총괄 2',
      roleSlug: 'director_2',
      isMe: false,
    },
  ],
  totalDepartments: 3,
  departments: [
    {
      id: 'dept1',
      name: '영업부',
      departmentHead: {
        memberId: 'dh1',
        userId: 'u3',
        fullName: '이서연',
        avatarUrl: 'https://i.pravatar.cc/100?img=5',
        role: '본부장',
        roleSlug: 'department_head',
        isMe: false,
      },
      teams: [
        {
          id: 'team1',
          name: '국내영업팀',
          isDefault: true,
          members: [
            {
              memberId: 'm1',
              userId: 'u4',
              fullName: '박지호',
              avatarUrl: 'https://i.pravatar.cc/100?img=33',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm2',
              userId: 'u5',
              fullName: '최수아',
              avatarUrl: 'https://i.pravatar.cc/100?img=44',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm3',
              userId: 'u6',
              fullName: '정도윤',
              avatarUrl: 'https://i.pravatar.cc/100?img=52',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm4',
              userId: 'u7',
              fullName: '강태양',
              avatarUrl: 'https://i.pravatar.cc/100?img=53',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
        {
          id: 'team2',
          name: '해외영업팀',
          isDefault: false,
          members: [
            {
              memberId: 'm5',
              userId: 'u8',
              fullName: '강다니엘',
              avatarUrl: 'https://i.pravatar.cc/100?img=14',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm6',
              userId: 'u9',
              fullName: '조하은',
              avatarUrl: 'https://i.pravatar.cc/100?img=20',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm7',
              userId: 'u10',
              fullName: '윤시우',
              avatarUrl: 'https://i.pravatar.cc/100?img=25',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm8',
              userId: 'u11',
              fullName: '장나라',
              avatarUrl: 'https://i.pravatar.cc/100?img=26',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm9',
              userId: 'u12',
              fullName: '한지민',
              avatarUrl: 'https://i.pravatar.cc/100?img=27',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm10',
              userId: 'u13',
              fullName: '김태리',
              avatarUrl: 'https://i.pravatar.cc/100?img=28',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm11',
              userId: 'u14',
              fullName: '이민호',
              avatarUrl: 'https://i.pravatar.cc/100?img=29',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm12',
              userId: 'u15',
              fullName: '송혜교',
              avatarUrl: 'https://i.pravatar.cc/100?img=30',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm13',
              userId: 'u16',
              fullName: '박보영',
              avatarUrl: 'https://i.pravatar.cc/100?img=31',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm14',
              userId: 'u17',
              fullName: '서강준',
              avatarUrl: 'https://i.pravatar.cc/100?img=32',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
      ],
    },
    {
      id: 'dept2',
      name: '마케팅부',
      departmentHead: {
        memberId: 'dh2',
        userId: 'u18',
        fullName: '이준혁',
        avatarUrl: 'https://i.pravatar.cc/100?img=57',
        role: '본부장',
        roleSlug: 'department_head',
        isMe: false,
      },
      teams: [
        {
          id: 'team3',
          name: '브랜드마케팅팀',
          isDefault: true,
          members: [
            {
              memberId: 'm15',
              userId: 'u19',
              fullName: '박서준',
              avatarUrl: 'https://i.pravatar.cc/100?img=59',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm16',
              userId: 'u20',
              fullName: '최예린',
              avatarUrl: 'https://i.pravatar.cc/100?img=45',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm17',
              userId: 'u21',
              fullName: '정우성',
              avatarUrl: 'https://i.pravatar.cc/100?img=60',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm18',
              userId: 'u22',
              fullName: '강다은',
              avatarUrl: 'https://i.pravatar.cc/100?img=47',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
        {
          id: 'team4',
          name: '콘텐츠팀',
          isDefault: false,
          members: [
            {
              memberId: 'm19',
              userId: 'u23',
              fullName: '조민서',
              avatarUrl: 'https://i.pravatar.cc/100?img=36',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm20',
              userId: 'u24',
              fullName: '윤아름',
              avatarUrl: 'https://i.pravatar.cc/100?img=38',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm21',
              userId: 'u25',
              fullName: '장현우',
              avatarUrl: 'https://i.pravatar.cc/100?img=61',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm22',
              userId: 'u26',
              fullName: '한소희',
              avatarUrl: 'https://i.pravatar.cc/100?img=41',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm23',
              userId: 'u27',
              fullName: '신지훈',
              avatarUrl: 'https://i.pravatar.cc/100?img=62',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm24',
              userId: 'u28',
              fullName: '김수현',
              avatarUrl: 'https://i.pravatar.cc/100?img=63',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm25',
              userId: 'u29',
              fullName: '이지은',
              avatarUrl: 'https://i.pravatar.cc/100?img=43',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm26',
              userId: 'u30',
              fullName: '전지현',
              avatarUrl: 'https://i.pravatar.cc/100?img=48',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm27',
              userId: 'u31',
              fullName: '공유준',
              avatarUrl: 'https://i.pravatar.cc/100?img=65',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm28',
              userId: 'u32',
              fullName: '손예진',
              avatarUrl: 'https://i.pravatar.cc/100?img=49',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
      ],
    },
    {
      id: 'dept3',
      name: '재무부',
      departmentHead: {
        memberId: 'dh3',
        userId: 'u33',
        fullName: '박지성',
        avatarUrl: 'https://i.pravatar.cc/100?img=68',
        role: '본부장',
        roleSlug: 'department_head',
        isMe: false,
      },
      teams: [
        {
          id: 'team5',
          name: '회계팀',
          isDefault: true,
          members: [
            {
              memberId: 'm29',
              userId: 'u34',
              fullName: '김영란',
              avatarUrl: 'https://i.pravatar.cc/100?img=46',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm30',
              userId: 'u35',
              fullName: '이동욱',
              avatarUrl: 'https://i.pravatar.cc/100?img=67',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm31',
              userId: 'u36',
              fullName: '정해인',
              avatarUrl: 'https://i.pravatar.cc/100?img=50',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm32',
              userId: 'u37',
              fullName: '배수지',
              avatarUrl: 'https://i.pravatar.cc/100?img=51',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
        {
          id: 'team6',
          name: '재무관리팀',
          isDefault: false,
          members: [
            {
              memberId: 'm33',
              userId: 'u38',
              fullName: '유연석',
              avatarUrl: 'https://i.pravatar.cc/100?img=54',
              role: '팀장',
              roleSlug: 'team_leader',
              isMe: false,
            },
            {
              memberId: 'm34',
              userId: 'u39',
              fullName: '한가인',
              avatarUrl: 'https://i.pravatar.cc/100?img=55',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
            {
              memberId: 'm35',
              userId: 'u40',
              fullName: '조승우',
              avatarUrl: 'https://i.pravatar.cc/100?img=56',
              role: '팀원',
              roleSlug: 'member',
              isMe: false,
            },
          ],
        },
      ],
    },
  ],
};
